### ISSUE TITLE
Exposed Password in sendMail/sendMail.js

### ISSUE THREAD

**Issue by arya2004** [apoorvapendse/Medonor-groupO9#12]
A password is exposed in `sendMail/sendMail.js` on line number 9.
it is advisable to store such sensitive information in .env file

**Comment by apoorvapendse** [comment]
Thanks for the suggestion

**Comment by apoorvapendse** [comment]
solved in 0ff2d27

**Comment by apoorvapendse** [comment]
solved in 0ff2d27
